# Generated by Django 6.0 on 2026-01-23 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.CharField(max_length=165)),
                ('slug', models.SlugField(unique=True)),
                ('tempo_preparo', models.IntegerField(help_text='Tempo em minutos')),
                ('tempo_preparo_unidade', models.CharField(max_length=65)),
                ('porcoes', models.IntegerField()),
                ('porcoes_unidade', models.CharField(max_length=65)),
                ('modo_preparo', models.TextField()),
                ('modo_preparo_is_html', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='receitas/covers/%Y/%m/%d/')),
                ('ingredientes', models.TextField()),
                ('rendimento', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='receitas.author')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='receitas.categoria')),
            ],
        ),
    ]
